site_name: GHGPy Docs

theme:
  name: "material"

plugins:
  - mkdocstrings
  - search

nav:
  - index.md
  - About: about.md
  - Getting Started: getting_started.md
  - Reference: reference.md
  - Patch History: patch_history.md
  - License: license.md